# 常量定义
TILE_SIZE = 32
GRID_SIZE = 23  # 游戏地图的网格大小
IMG_SIZE = 32
SCOREBOARD_WIDTH = 250  # 计分板宽度
SCREEN_WIDTH = GRID_SIZE * TILE_SIZE + SCOREBOARD_WIDTH
SCREEN_HEIGHT = GRID_SIZE * TILE_SIZE

# 颜色定义
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (100, 100, 100)
RED = (255, 0, 0)
BLUE = (0, 0, 255)

# 石块类型
class TileType:
    UNBREAKABLE = 0
    BREAKABLE = 1
    EMPTY = 2
    AROUND = 3
    BUFF_RANGE = 4
    BUFF_NUM = 5
    HEAL = 6
    GRASS_BUFF_RANGE = 7
    GRASS_BUFF_NUM = 8
    GRASS_HEAL = 9